class HeaderLocators:
    email_sign_up = '//*[@id="__next"]/header/div/div/div/ul/li/a'
    logo = '//*[@id="__next"]/header/nav/div/div/ul/li[1]/a'
    products = '//*[@id=":R1kcmH2:"]/a'
    all_products = '// *[ @ id = ":R1kcmH1:"] / button[1] / a'
    daily_moisture = '// *[ @ id = ":R1kcmH1:"] / button[2] / a'
    advance_therapy = '// *[ @ id = ":R1kcmH1:"] / button[3] / a'
    intense_skin_repair = '// *[ @ id = ":R1kcmH1:"] / button[4] / a'
    skin_concerns = '//*[@id=":R2kcmH2:"]/a'
    all_skin_concerns = '// *[ @ id = ":R2kcmH1:"] / button[1] / a'
    normal_to_dry_skin= '// *[ @ id = ":R2kcmH1:"] / button[2] / a'
    extra_dry_skin = '// *[ @ id = ":R2kcmH1:"] / button[3] / a'
    mature_skin_care = '// *[ @ id = ":R2kcmH1:"] / button[4] / a'
    tattoo_after_care = '// *[ @ id = ":R2kcmH1:"] / button[5] / a'
    itchy_dry_skin = '// *[ @ id = ":R2kcmH1:"] / button[6] / a'
    about_lubriderm = '//*[@id=":R3kcmH2:"]/a'
    overview = '// *[ @ id = ":R3kcmH1:"] / button[1] / a'
    our_ingredients = '// *[ @ id = ":R3kcmH1:"] / button[2] / a'
    contact_us = '// *[ @ id = ":R3kcmH1:"] / button[3] / a'
    where_to_buy = '//*[@id="__next"]/header/nav/div/div/ul/li[2]/a'
