class HomepageLocators:
    banner_cta = '//*[@id="__next"]/main/div[1]/div[2]/div/a/button'
    banner_header_text = '//*[@id="__next"]/main/div[1]/div[2]/div/h1'
    banner_sub_copy_text = '//*[@id="__next"]/main/div[1]/div[2]/div/p'
    banner_image = '//*[@id="__next"]/main/div[1]/div[1]/img'
    our_products_section = '//*[@id="__next"]/main/div[2]/h2[1]/span'
    see_all_products = '//*[@id="__next"]/main/div[2]/a[1]/button'
    product1_image = '//*[@id="__next"]/main/div[2]/div[1]/div[1]/div[1]/a/img'
    product1_cta = '//*[@id="__next"]/main/div[2]/div[1]/div[1]/div[2]/a'
    product2_image = '//*[@id="__next"]/main/div[2]/div[1]/div[2]/div[1]/a/img'
    product2_cta = '//*[@id="__next"]/main/div[2]/div[1]/div[2]/div[2]/a'
    product3_image = '//*[@id="__next"]/main/div[2]/div[1]/div[3]/div[1]/a/img'
    product3_cta = '//*[@id="__next"]/main/div[2]/div[1]/div[3]/div[2]/a'
    our_bestseller = '//*[@id="__next"]/main/div[2]/h2[2]/span'
    product1_card_image = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[1]/div/div/div[1]/a/img'
    product1_card_name = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[1]/div/div/div[2]/a'
    buy_now1 = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[1]/div/div/div[3]/div[2]/div'
    price_spider_pop_up1 = 'ps-container ps-lightbox ps-6462c37d7d0774004fa25168 ps-open'
    price_spider_pop_up1_close = 'ps-lightbox-close'
    product2_card_image = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[2]/div/div/div[1]/a/img'
    product2_card_name = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[2]/div/div/div[2]/a'
    buy_now2 = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[2]/div/div/div[3]/div[2]/div'
    price_spider_pop_up2 = 'ps-container ps-lightbox ps-6462c37d7d0774004fa25168 ps-open'
    price_spider_pop_up2_close = 'ps-lightbox-close'
    product3_card_image = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[3]/div/div/div[1]/a/img'
    product3_card_name = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[3]/div/div/div[2]/a'
    buy_now3 = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[3]/div/div/div[3]/div[2]/div'
    price_spider_pop_up3 = 'ps-container ps-lightbox ps-6462c37d7d0774004fa25168 ps-open'
    price_spider_pop_up3_close = 'ps-lightbox-close'
    skin_concerns_section = '//*[@id="__next"]/main/div[2]/h2[3]/span'
    all_skin_concerns = '//*[@id="__next"]/main/div[2]/a[2]/button'
    skin_concerns1_image = '//*[@id="__next"]/main/div[2]/div[5]/div[1]/div[1]/a/img'
    skin_concerns1_cta = '//*[@id="__next"]/main/div[2]/div[5]/div[1]/div[2]/a'
    skin_concerns2_image = '//*[@id="__next"]/main/div[2]/div[5]/div[2]/div[1]/a/img'
    skin_concerns2_cta = '//*[@id="__next"]/main/div[2]/div[5]/div[2]/div[2]/a'
    skin_concerns3_image = '//*[@id="__next"]/main/div[2]/div[5]/div[3]/div[1]/a/img'
    skin_concerns3_cta = '//*[@id="__next"]/main/div[2]/div[5]/div[3]/div[2]/a'
    skin_concerns4_image = '//*[@id="__next"]/main/div[2]/div[5]/div[4]/div[1]/a/img'
    skin_concerns4_cta = '//*[@id="__next"]/main/div[2]/div[5]/div[4]/div[2]/a'
    related_content = '//*[@id="__next"]/main/div[2]/h2[4]/span'
    related_content_image1 = '//*[@id="__next"]/main/div[2]/div[7]/div[1]/div[1]/a/img'
    related_content_header1_text = '//*[@id="__next"]/main/div[2]/div[7]/div[1]/div[2]/p'
    related_content1_cta = '//*[@id="__next"]/main/div[2]/div[7]/div[1]/div[2]/a'
    related_content_image2 = '//*[@id="__next"]/main/div[2]/div[7]/div[2]/div[1]/a/img'
    related_content_header2_text = '//*[@id="__next"]/main/div[2]/div[7]/div[2]/div[2]/p'
    related_content2_cta = '//*[@id="__next"]/main/div[2]/div[7]/div[2]/div[2]/a'
