class HomepageLocators:
    banner_cta = '//*[@id="__next"]/main/div[1]/div[2]/div/a/button'
    banner_header_text = '//*[@id="__next"]/main/div[1]/div[2]/div/h1'
    banner_sub_copy_text = '//*[@id="__next"]/main/div[1]/div[2]/div/p'
    banner_image = '//*[@id="__next"]/main/div[1]/div[1]/img'
    our_products_section = '//*[@id="__next"]/main/div[2]/h2[1]/span'
    see_all_products = '//*[@id="__next"]/main/div[2]/a[1]/button'
    product1_image = '//*[@id="__next"]/main/div[2]/div[1]/div[1]/div[1]/a/img'
    product1_cta = '//*[@id="__next"]/main/div[2]/div[1]/div[1]/div[2]/a'
    product2_image = '//*[@id="__next"]/main/div[2]/div[1]/div[2]/div[1]/a/img'
    product2_cta = '//*[@id="__next"]/main/div[2]/div[1]/div[2]/div[2]/a'
    product3_image = '//*[@id="__next"]/main/div[2]/div[1]/div[3]/div[1]/a/img'
    product3_cta = '//*[@id="__next"]/main/div[2]/div[1]/div[3]/div[2]/a'
    our_bestseller = '//*[@id="__next"]/main/div[2]/h2[2]/span'
    product1_card_image = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[1]/div/div/div[1]/a/img'
    product1_card_name = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[1]/div/div/div[2]/a'
    buy_now1 = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[1]/div/div/div[3]/div[2]/div'
    price_spider_pop_up1 = '/html/body/div[9]/div'
    price_spider_pop_up1_close = '/html/body/div[9]/div/span'
##########################################################################
    product2_card_image = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[2]/div/div/div[1]/a/img'
    product2_card_name = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[2]/div/div/div[2]/a'
    buy_now2 = '//*[@id="__next"]/main/div[2]/div[3]/div/div/div/div/div[2]/div/div/div[3]/div[2]/div'
    price_spider_pop_up2 = '/html/body/div[11]'
    price_spider_pop_up2_close = '/html/body/div[11]/div/span'

    