class PDP1Locators:
    close_bottom_pop_up = '//*[@id="onetrust-close-btn-container"]/button'
    product_over_view_div = '//*[@id="product-overview"]'
    main_image = '//*[@id="product-overview"]/div[1]/div/div/div[3]/div/div/div[1]/div/div/img'
    down_arrow = '//*[@id="product-overview"]/div[1]/div/div/div[1]/div/div[3]/div/button'
    up_arrow = '//*[@id="product-overview"]/div[1]/div/div/div[1]/div/div[1]/div/button'
    slide_dot2 = '//*[@id="product-overview"]/div[1]/div/div/div[1]/div/div[2]/div/button[2]'
    slide_dot3 = '//*[@id="product-overview"]/div[1]/div/div/div[1]/div/div[2]/div/button[3]'
    slide_dot4 = '//*[@id="product-overview"]/div[1]/div/div/div[1]/div/div[2]/div/button[4]'
    slide_dot5 = '//*[@id="product-overview"]/div[1]/div/div/div[1]/div/div[2]/div/button[5]'
    image2 = '//*[@id="product-overview"]/div[1]/div/div/div[3]/div/div/div[2]/div/div/img'
    image3 = '//*[@id="product-overview"]/div[1]/div/div/div[3]/div/div/div[3]/div/div/img'
    image4 = '//*[@id="product-overview"]/div[1]/div/div/div[3]/div/div/div[4]/div/div/img'
    image5 = '//*[@id="product-overview"]/div[1]/div/div/div[3]/div/div/div[5]/div/div/img'
    h1_title = '//*[@id="product-overview"]/div[2]/h1'
    eyebrow = '//*[@id="product-overview"]/div[2]/p'
    star_review = '//*[@id="product-overview"]/div[2]/div[1]'
    buy_now_cta = '//*[@id="product-overview"]/div[2]/div[2]/div/div'
    price_spider_pop_up = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div"
    price_spider_pop_up_close = "body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div > span"
    product_details = '//*[@id="product-overview"]/div[2]/div[3]'
    jump_to_links = '//*[@id="__next"]/main/section/div[2]/div/div/div'
    jum_to_links_lists = '//*[@id="__next"]/main/section/div[2]/div/div/div/ul'
    product_over_view = '//*[@id="__next"]/main/section/div[2]/div/div/div/ul/li[2]'
    ingredients = '//*[@id="__next"]/main/section/div[2]/div/div/div/ul/li[3]'
    you_may_also_like = '//*[@id="__next"]/main/section/div[2]/div/div/div/ul/li[4]'
    reviews = '//*[@id="__next"]/main/section/div[2]/div/div/div/ul/li[5]'
    ingredients_section = '//*[@id="ingredients"]'
    you_may_also_like_section = '//*[@id="in-this-collection"]'
    review_section = '//*[@id="reviews"]'
    ingredients_header = '//*[@id="ingredients"]/h3'
    ingredients_image = '//*[@id="ingredients"]/div/img'
    ingredients_texts = '//*[@id="ingredients"]/div/div/p'
    ingredients_cta = '//*[@id="ingredients"]/div/div/a'
    you_may_also_like_header = '//*[@id="in-this-collection"]/h3'
    product1_card_image = '//*[@id="in-this-collection"]/div/div/div/div/div/div[1]/div/div/div[1]/a'
    product1_card_name = '//*[@id="in-this-collection"]/div/div/div/div/div/div[1]/div/div/div[2]/a'
    buy_now_cta1 = '//*[@id="in-this-collection"]/div/div/div/div/div/div[1]/div/div/div[3]/div[2]/div'
    price_spider_pop_up1 = 'body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div'
    price_spider_pop_up1_close = 'body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div > span'
    product2_card_image = '//*[@id="in-this-collection"]/div/div/div/div/div/div[2]/div/div/div[1]/a'
    product2_card_name = '//*[@id="in-this-collection"]/div/div/div/div/div/div[2]/div/div/div[2]/a'
    buy_now_cta2 = '//*[@id="in-this-collection"]/div/div/div/div/div/div[2]/div/div/div[3]/div[2]/div'
    price_spider_pop_up2 = 'body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div'
    price_spider_pop_up2_close = 'body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div > span'
    product3_card_image = '//*[@id="in-this-collection"]/div/div/div/div/div/div[3]/div/div/div[1]/a'
    product3_card_name = '//*[@id="in-this-collection"]/div/div/div/div/div/div[3]/div/div/div[2]/a'
    buy_now_cta3 = '//*[@id="in-this-collection"]/div/div/div/div/div/div[3]/div/div/div[3]/div[2]/div'
    price_spider_pop_up3 = 'body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div'
    price_spider_pop_up3_close = 'body > div.ps-container.ps-lightbox.ps-6462c37d7d0774004fa25168.ps-open > div > span'
